---
- hosts: all
  become: true
  tasks:
    - name: Group by OS
      group_by: key=os_{{ ansible_distribution }}
      changed_when: False

- hosts: os_RedHat
  become: true
  roles:
    - ansible-role-rhel-patchmanagement 
